const countries = [
    { code: "+1", flag: "🇺🇸", name: "United States" },
    { code: "+1", flag: "🇨🇦", name: "Canada" },
    { code: "+961", flag: "🇱🇧", name: "Lebanon" },
    { code: "+33", flag: "🇫🇷", name: "France" },
    { code: "+49", flag: "🇩🇪", name: "Germany" },
    { code: "+44", flag: "🇬🇧", name: "United Kingdom" },
    { code: "+39", flag: "🇮🇹", name: "Italy" },
    { code: "+34", flag: "🇪🇸", name: "Spain" },
    { code: "+31", flag: "🇳🇱", name: "Netherlands" },
    { code: "+41", flag: "🇨🇭", name: "Switzerland" },
    { code: "+43", flag: "🇦🇹", name: "Austria" },
    { code: "+32", flag: "🇧🇪", name: "Belgium" },
    { code: "+45", flag: "🇩🇰", name: "Denmark" },
    { code: "+46", flag: "🇸🇪", name: "Sweden" },
    { code: "+47", flag: "🇳🇴", name: "Norway" },
    { code: "+358", flag: "🇫🇮", name: "Finland" },
    { code: "+351", flag: "🇵🇹", name: "Portugal" },
    { code: "+30", flag: "🇬🇷", name: "Greece" },
    { code: "+48", flag: "🇵🇱", name: "Poland" },
    { code: "+420", flag: "🇨🇿", name: "Czech Republic" },
    { code: "+36", flag: "🇭🇺", name: "Hungary" },
    { code: "+40", flag: "🇷🇴", name: "Romania" },
    { code: "+359", flag: "🇧🇬", name: "Bulgaria" },
    { code: "+385", flag: "🇭🇷", name: "Croatia" },
    { code: "+386", flag: "🇸🇮", name: "Slovenia" },
    { code: "+421", flag: "🇸🇰", name: "Slovakia" },
    { code: "+372", flag: "🇪🇪", name: "Estonia" },
    { code: "+371", flag: "🇱🇻", name: "Latvia" },
    { code: "+370", flag: "🇱🇹", name: "Lithuania" },
    { code: "+7", flag: "🇷🇺", name: "Russia" },
    { code: "+380", flag: "🇺🇦", name: "Ukraine" },
    { code: "+375", flag: "🇧🇾", name: "Belarus" },
    { code: "+90", flag: "🇹🇷", name: "Turkey" },
    { code: "+972", flag: "🇮🇱", name: "Israel" },
    { code: "+966", flag: "🇸🇦", name: "Saudi Arabia" },
    { code: "+971", flag: "🇦🇪", name: "United Arab Emirates" },
    { code: "+974", flag: "🇶🇦", name: "Qatar" },
    { code: "+965", flag: "🇰🇼", name: "Kuwait" },
    { code: "+973", flag: "🇧🇭", name: "Bahrain" },
    { code: "+968", flag: "🇴🇲", name: "Oman" },
    { code: "+962", flag: "🇯🇴", name: "Jordan" },
    { code: "+963", flag: "🇸🇾", name: "Syria" },
    { code: "+964", flag: "🇮🇶", name: "Iraq" },
    { code: "+20", flag: "🇪🇬", name: "Egypt" },
    { code: "+212", flag: "🇲🇦", name: "Morocco" },
    { code: "+213", flag: "🇩🇿", name: "Algeria" },
    { code: "+216", flag: "🇹🇳", name: "Tunisia" },
    { code: "+218", flag: "🇱🇾", name: "Libya" },
    { code: "+249", flag: "🇸🇩", name: "Sudan" },
    { code: "+251", flag: "🇪🇹", name: "Ethiopia" },
    { code: "+254", flag: "🇰🇪", name: "Kenya" },
    { code: "+255", flag: "🇹🇿", name: "Tanzania" },
    { code: "+256", flag: "🇺🇬", name: "Uganda" },
    { code: "+234", flag: "🇳🇬", name: "Nigeria" },
    { code: "+233", flag: "🇬🇭", name: "Ghana" },
    { code: "+27", flag: "🇿🇦", name: "South Africa" },
    { code: "+91", flag: "🇮🇳", name: "India" },
    { code: "+92", flag: "🇵🇰", name: "Pakistan" },
    { code: "+880", flag: "🇧🇩", name: "Bangladesh" },
    { code: "+94", flag: "🇱🇰", name: "Sri Lanka" },
    { code: "+977", flag: "🇳🇵", name: "Nepal" },
    { code: "+86", flag: "🇨🇳", name: "China" },
    { code: "+81", flag: "🇯🇵", name: "Japan" },
    { code: "+82", flag: "🇰🇷", name: "South Korea" },
    { code: "+66", flag: "🇹🇭", name: "Thailand" },
    { code: "+84", flag: "🇻🇳", name: "Vietnam" },
    { code: "+60", flag: "🇲🇾", name: "Malaysia" },
    { code: "+65", flag: "🇸🇬", name: "Singapore" },
    { code: "+63", flag: "🇵🇭", name: "Philippines" },
    { code: "+62", flag: "🇮🇩", name: "Indonesia" },
    { code: "+61", flag: "🇦🇺", name: "Australia" },
    { code: "+64", flag: "🇳🇿", name: "New Zealand" },
    { code: "+55", flag: "🇧🇷", name: "Brazil" },
    { code: "+54", flag: "🇦🇷", name: "Argentina" },
    { code: "+56", flag: "🇨🇱", name: "Chile" },
    { code: "+57", flag: "🇨🇴", name: "Colombia" },
    { code: "+51", flag: "🇵🇪", name: "Peru" },
    { code: "+58", flag: "🇻🇪", name: "Venezuela" },
    { code: "+52", flag: "🇲🇽", name: "Mexico" },
];

export default countries;